name: log-tracing-clickhouse
services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.4.4.38
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"   # HTTP API
      - "9002:9000"   # Native TCP client
      - "9363:9363"   # Prometheus metrics
    environment:
      CLICKHOUSE_DB: log_db
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./docker/clickhouse/config.d/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml:ro
      - ./docker/clickhouse/init:/docker-entrypoint-initdb.d:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "admin", "--password", "admin123", "--query", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: ch-ui
    restart: unless-stopped
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "3488:3488"
    environment:
      CLICKHOUSE_URL: "http://clickhouse:8123"
      CONNECTION_NAME: "Local ClickHouse"
      APP_SECRET_KEY: "fsdfsdfsdfsdfdsfsdfds"
    volumes:
      - ch_ui_data:/app/data

volumes:
  clickhouse_data:
  clickhouse_logs:
  ch_ui_data:
